name: jamf_design_system_package
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen: ^5.6.0
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/fonts/
    - assets/colors/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.ttf
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-BlackItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-Light.ttf
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-Ultralight.ttf
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
        - asset: assets/fonts/SF-Pro-Display-LightItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-Heavy.ttf
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.ttf
        - asset: assets/fonts/SF-Pro-Display-Thin.ttf

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    outputs:
      class_name: JamfAssetsFoundation
  fonts:
    enabled: true
    outputs:
      class_name: JamfFontFamilyToken
  colors:
    enabled: true
    outputs:
      class_name: JamfColorsToken
    inputs:
      - assets/colors/colors.xml